# Generated by Django 3.1.2 on 2020-10-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг страницы')),
                ('embed_url', models.TextField(unique=True, verbose_name='Ссылка на видео')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('script', models.TextField(verbose_name='Скрипт урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='TimeCodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=5, verbose_name='Старт')),
                ('finish', models.CharField(max_length=5, verbose_name='Конец')),
                ('attached_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lessonmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AttachedLinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('attached_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lessonmodel')),
            ],
        ),
    ]
