# Generated by Django 3.1.2 on 2020-11-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_currentlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecodemodel',
            name='label',
            field=models.CharField(default='Таймкод', max_length=200, verbose_name='Подпись'),
        ),
    ]
