# Generated by Django 3.1.2 on 2020-11-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_timecodemodel_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedlinkmodel',
            name='label',
            field=models.CharField(default='Полезная ссылка', max_length=300, verbose_name='Подпись'),
        ),
    ]
