# Generated by Django 3.1.3 on 2020-11-21 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0005_auto_20201121_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lessonmodel', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Домашка',
                'verbose_name_plural': 'Домашки',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_input', models.TextField(verbose_name='Входные данные')),
                ('test_output', models.TextField(verbose_name='Вывод')),
                ('attached_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.homeworkmodel')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
