# Generated by Django 3.1.3 on 2020-11-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20201121_1613'),
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkmodel',
            name='decs',
            field=models.TextField(default='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='homeworkmodel',
            name='attached_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lessonmodel', unique=True, verbose_name='Урок'),
        ),
    ]
