# Generated by Django 3.1.3 on 2020-11-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20201121_1613'),
        ('compiler', '0002_auto_20201122_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivenHomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=150, unique=True)),
                ('status', models.CharField(choices=[('done', 'Done'), ('notdone', 'NotDone')], max_length=50)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lessonmodel')),
            ],
        ),
    ]
