# Generated by Django 3.1.3 on 2020-11-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_givenhomework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givenhomework',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('notdone', 'NotDone')], default='notdone', max_length=50),
        ),
        migrations.AlterField(
            model_name='givenhomework',
            name='user',
            field=models.TextField(max_length=150),
        ),
    ]
